Geographical migration #94
obo-behavior/behavior-ontology pull request #172
Opened 2023-04-22 14:59 UTC by DitchingIt

2023-04-25 15:39 UTC, DitchingIt commented
Fixes #94

2023-04-27 10:31 UTC, matentzn requested changes

2023-04-27 10:31 UTC, matentzn commented on src/ontology/nbo-edit.owl
> +AnnotationAssertion(obo:IAO_0000115 obo:NBO_0070001 "Rhythmic behavior that involves cue-initiated, persistent, direct, focused movement between habitats.")
Missing source

2023-05-01 13:22 UTC, matentzn commented on src/ontology/nbo-edit.owl
> +AnnotationAssertion(terms:contributor obo:NBO_0070003 <https://orcid.org/0000-0002-4277-2151>)
You sometimes use `terms:contributor` and other times `dc:contributor` - you should only ever use the former.

2023-05-01 14:07 UTC, matentzn commented
This PR is broken now - you should redo it from scratch; its conflicting with all the other PRs you did previously.

2023-05-01 14:40 UTC, closed without merging