NTR vaping behavior
obo-behavior/behavior-ontology pull request #198
Opened 2023-11-29 14:23 UTC by DitchingIt

Creates a new term and child relations to tobacco and cannabis vaping as requested in issue #195

2023-11-29 22:51 UTC, pmidford commented
Are we still accepting behaviors that are more or less exclusive to humans and occasional model organisms?  I thought there was an alternative ontology for these.

2023-11-30 08:55 UTC, DitchingIt commented
> Are we still accepting behaviors that are more or less exclusive to humans and occasional model organisms? I thought there was an alternative ontology for these.

Hi @pmidford There aren't yet any plans to deprecate human or animal model behaviours, although it has been discussed. I'm not putting my own efforts into these areas but am happy to encourage others wanting to interact with NBO by helping with the odd thing like a commit, not least where all the thinking has already been done (like here), but you'll note I'm not attempting to impose the styling I'd look for if it was an Ethology edit. Would you be happy to approve this? If OP had made the commit, I would have, but because I wrote it up, GitHub needs someone else.

2023-11-30 09:56 UTC, matentzn requested changes

2023-11-30 09:56 UTC, matentzn commented on src/ontology/nbo-edit.owl
> +Declaration(Class(<http://purl.obolibrary.org/obo/nbo.owl/NBO_0070027>))
Something went wront with your protege config.

1. Open nbo on this branch
1. Click on the new class
2. Click (in menu) on "refactor"-->"rename entity"
3. Click "show full IRI"
4. Change to `http://purl.obolibrary.org/obo/NBO_0070027` (without the nbo.owl)
5. Safe, commit, push

2023-11-30 18:42 UTC, matthewhorridge approved these changes
This looks good.  @DitchingIt thanks so much for this and for the really quick turnaround time.

2023-11-30 20:51 UTC, DitchingIt commented
@pmidford @matthewhorridge Can someone review and approve the changes I made resolving @matentzn change request? Then I think we're done.

2023-11-30 21:00 UTC, matentzn approved these changes
looks great

2023-11-30 21:00 UTC, merged